# Generated by Django 3.2 on 2023-02-16 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default='1', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимальный рейтинг - 1'), django.core.validators.MaxValueValidator(limit_value=10, message='Максимальный рейтинг - 10')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(help_text='Введите текст отзыва', verbose_name='Текст отзыва'),
        ),
    ]
