# Generated by Django 3.2 on 2023-02-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_category_options'),
        ('reviews', '0004_auto_20230218_1943'),
        ('reviews', '0004_auto_20230218_2258'),
    ]

    operations = [
    ]
